services:
  vprodb:
    build: 
      context: ./Docker-file/db
    image: welkom1/kelvindb  # Corrected from "images" to "image"
    container_name: vprodb
    environment:
      MYSQL_ROOT_PASSWORD: "welkom01"
    volumes:
      - vprodbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vprmq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: welkom1/kelvinapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

volumes:
  vprodbdata:
  vproappdata:
